### ISSUE TITLE
Debian stretch (9.0) release date announced: 2017-06-17

### ISSUE THREAD

**Issue by neuffer** [sovereign/sovereign#695]
The planned release date for Debian stretch (9.0) has just been announced: 2017-06-17

This is less then a month away, so the question arises if anybody has already tested Sovereign with current Debian stretch ?

**Comment by erlepereira** [comment]
I was experimenting with it some days ago, there might be some updates required...don't think too much. Will give it another go & report back. Managed to patch some, so might be able to send a patch across too if needed.

**Comment by neuffer** [comment]
On 06.06.2017 07:09, Erle Pereira wrote:
>
> I was experimenting with it some days ago, there might be some updates
> required...don't think too much. Will give it another go & report
> back. Managed to patch some, so might be able to send a patch across
> too if needed.
>

That would be great.
:-)

**Comment by erlepereira** [comment]
quick update:
Ran this against stretch-rc3. I now have the common tasks working. There are a heap of minor stuff, I have attached my personal notes "brain-dump here to what was changed & a patch which does whats needed to get the first list of common tasks going. 

This should probably tracked individually to keep a track of what was changed and why, and patch each item as a pull request etc... for now I have attached the patch here instead for anyone wanting to have a go. 

_with this it now fails at : TASK [mailserver : Update post-certificate-renewal task]  
... (working on it)_

[update-stretch.txt](https://github.com/sovereign/sovereign/files/1067020/update-stretch.txt)

[commonTasks_jessietostretch.patch.txt](https://github.com/sovereign/sovereign/files/1067021/commonTasks_jessietostretch.patch.txt)

Environment I am using to test:
* Ansible 2.2.1.0
* Stretch was installed in an LXC container -- to get encfs working, a once off manual config needed see comment https://github.com/sovereign/sovereign/issues/665#issuecomment-303616978

**Comment by neuhaus** [comment]
What's the verdict, do we need a new branch for Debian 9 or can it coexist on the same branch?

**Comment by erlepereira** [comment]
While I think its "doable" in the same branch, from what I've seen...a few conditionals and we are there.

From the bigger picture ... might be harder to co-exist on the current branch and ensure jessie compatibility too. It might make sense to branch & incorporate the other issue discussions (best practices, v2, release versions etc.) That way we can take advantage of newer ansible versions and improve on the playbook conditionals as well.

**Comment by mikeashley** [comment]
I looked at the release notes for Stretch.  The biggest risk looked like the switch from MySQL to MariaDB, but we don't use MySQL much at this point.  A number of packages including Postfix took major version number bumps.  There could be configuration file changes.  We won't know for sure until we see the patches.

Realistically, can we support two releases of any operating system?  Our testing support is still pretty poor.  If we support both Jessie and Stretch, every patch forward is going to beg the question: "what release did you test on" and maintainers would have to accept the risk of merging patches that are untested on one OS release or the other.

**Comment by neuhaus** [comment]
We have to weigh the benefits of a separate branch against its disadvantages (most importantly having to track issues and apply fixes to all relevant branches).

If the patches are small (for now) we may want to postpone the branching until there's a good reason to (could be mid-release).

**Comment by nodiscc** [comment]
FYI I just update my ansible playbooks for Debian Stretch and the breaking changes were:

 * php packages names have changed, there is no `apache2-mpm-*` packages anymore (https://github.com/nodiscc/srv01/commit/e48508730868a9b282de8cd4bea05be8ffc035ee)
 * modsecurity-crs file naming/configuration has changed (https://github.com/nodiscc/srv01/commit/231ceac730d48215dd440837c4b4fc11f9535dc4)

**Comment by neuffer** [comment]
Debian 9, "Stretch" has just been released
https://lists.debian.org/debian-announce/2017/msg00003.html

**Comment by erlepereira** [comment]
an update, On a fresh install upto the mailserver task, with some assumptions for now

* using mysql (should probably change it to mariadb(.... kept it for later
* some repos will not have stretch yet (rpsam for e.g.) -- using a variable to use jessie where possible for now

> TASK [mailserver : Install Rspamd, Rmilter, and Redis] ******************** *****
*  "msg": "No package matching 'rmilter' is available" 
-- the rmilter package is removed from stretch it seems. Looking deeper into this, also can we switch to the rspam version in stretch ?

[19jun2017.txt](https://github.com/sovereign/sovereign/files/1084763/19jun2017.txt)

* re the apache2-mpm package yeah. I have a patch for that, and the php names works ok, its not included in the patch above

**Comment by pjaspers** [comment]
> -- the rmilter package is removed from stretch it seems. Looking deeper into this, also can we switch to the rspam version in stretch ?

rspam is deprecating rmilter as of 1.6, so I think that's why it's gone.

**Comment by neuffer** [comment]
Upcoming stable point release (9.1)
The first point release for "stretch" (9.1) is scheduled for Saturday,
July 22nd.

**Comment by mikeashley** [comment]
MySQL and rmilter are goners with #720.

**Comment by arodier** [comment]
Thanks for sovereign, I found the project interesting, although I did not want to use it for myself.
If anyone is interested in hosting a mail server on Debian, I started a project myself.
It is on a smaller scale, with different goals, though.
https://github.com/progmaticltd/homebox

**Comment by neuhaus** [comment]
@arodier What would you say are the main differences between your homebox project and sovereign? It looks quite similar. Why didn't you want to use sovereign?

**Comment by arodier** [comment]
Hello Neuhaus,

First of all, I think Sovereign is really a great project, don't get me wrong. And you are very right, for an end user, the project probably does not make any difference, for now.

As myself, I have a few requirements I am not ready to make concessions. This is why I started my project, after checking all the projects around. In fact, I am hosting my emails myself for more than ten years.

- LDAP authentication and users management, no SQL.
- Staying inside official repositories, that push security updates (Debian, rspamd, etc.). No git clone / wget to install a package, _ever_.
- AppArmor support for security.
- Stability over new software versions, like Debian

For the home version:
- Automatic updates of external DNS entries (for now, Gandi)
- Automatic installer with LUKS partitionning
- Upnp support for router configuration

For hosted version: TBD

I have other ideas in mind, that will probably make differences, you will see later.

**Comment by pjaspers** [comment]
So, has anyone done the update?

My little arm box is missing a bunch of sources, so I'll probably need to do the upgrade.

**Comment by neuffer** [comment]
Just as a heads up, about a month ago Debian 10 (aka buster) was  [frozen](https://lists.debian.org/debian-devel-announce/2019/03/msg00003.html).
As of this moment there are 131  [RC bugs](https://bugs.debian.org/release-critical/other/testing.html). As soon as this is pushed down to 0, Debian 10 will be released. 
So preparations for Debian 10 would be in order.

**Comment by neuhaus** [comment]
Yes, we need more volunteers to work on this!
Please open a separate issue for work on Debian 10

**Comment by adborden** [comment]
What is the latest work for stretch, does anyone have a branch or is the best place to start from the patches linked?
- https://github.com/sovereign/sovereign/issues/695#issuecomment-307682440
- https://github.com/sovereign/sovereign/issues/695#issuecomment-309417863

**Comment by neuffer** [comment]
Issue for Debian 10.1 opened
https://github.com/sovereign/sovereign/issues/764

**Comment by adborden** [comment]
I have a [stretch branch](https://github.com/adborden/sovereign/tree/stretch-dev) working in vagrant. The playbooks run to completion without error but I'm sure it's not _actually_ working. I'm going to test it on jessie to make sure there's no regressions. Assuming that looks good, I would like to merge this to master and just include in the README that stretch is in development and still not supported.

From there, I'll open bugs for what's not working, and then we can move towards fixing the bugs until we get to full stretch support.

**Comment by adborden** [comment]
Would maintainers prefer I open GH issues for bugs, or that I keep an ongoing list within this issue?

**Comment by neuhaus** [comment]
In general it's good practice to open separate GH issues for every bug/issue.

**Comment by adborden** [comment]
Great, I'll create issues and link them here. Would you mind creating a [milestone](https://github.com/sovereign/sovereign/milestones) for stretch support and add any issues there?

**Comment by adborden** [comment]
Nevermind about the milestone, there's only a handful of issues, which I'll just track here.
- [ ] Ansible 2.6+ (#761)
- [ ] ZNC service will not start (#770)
- [ ] Cannot log into roundcube (#774)
- [ ] Missing PHP dependencies for OwnCloud (#775)

**Comment by mikeashley** [comment]
I updated my server to Stretch (Debian 9.9).  The owncloud crew stopped supporting Jessie some time ago, and that finally pushed me over the edge.  Here are the highlights:

- sync with new maintainer configuration files: ntp, ssh/sshd, dnsmasq, collectd, monit, dovecot
- update apache2 to use php 7 and drop php5 entirely
- update roundcube to 1.3.9
- update owncloud to 10.2
- update z-push to use their repository instead of tarballs

It was rather tedious but thankfully no major problems.  I was not running any mysql so didn't have to deal with the MariaDB switch.  I'm preparing a set of patches.  I recommend we just move master up to Stretch.

I glanced at Buster.  Some of our modules aren't releasing packages yet, e.g., z-push and owncloud.  I recommend we wait a while, e.g., next summer, before taking a hard look.

**Comment by neuhaus** [comment]
Nice. Do you happen to have a more detailed writeup we could turn into a wiki page for upgrading from Debian 8 to Debian 9?

**Comment by mikeashley** [comment]
Good thought.  I made a wiki page.  I also looked back at the Debian 7 to Debian 8 upgrade page.  This upgrade is a lot simpler.  When I said "tedious" above, I was referring to going through patches for configuration files.

**Comment by krmboya** [comment]
Hey all, thanks for all the good work on this project.

I'm wondering what a good starting point would be for someone currently doing their initial set up, given that long term support for Debian Jessie [ends in June][1]

[1]: https://www.debian.org/releases/jessie/

One option I see would be to set up in Debian jessie then upgrade the server to stretch as some have done here, but I would prefer a clean install on Debian 9 stretch if possible. I'm willing to contribute to any efforts to support Debian stretch in the process (I see a PR by @adborden attached to this issue).

I've also seen [this][2] discussion on Debian 10 'buster' support, but there doesn't seem to have been much traction.

[2]: https://github.com/sovereign/sovereign/issues/757

**Comment by krmboya** [comment]
Opened a draft PR building on @adborden work here: https://github.com/sovereign/sovereign/pull/820

Been working on it on and off in the past few months. Still testing and fixing things as I go. Feedback welcome.
